import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./app/**/*.{ts,tsx}",
    "./src/**/*.{ts,tsx}",
  ],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: { "2xl": "1400px" },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--appColor3))",
          foreground: "hsl(var(--foreground))",
        },
        // JMAN Brand token
        brand: {
          DEFAULT: "hsl(var(--brand))",
          foreground: "hsl(var(--brand-foreground))",
        },
        highlight: {
          DEFAULT: "hsl(var(--highlight))",
          foreground: "hsl(var(--highlight-foreground))",
        },
        // Sidebar  --  CSS-variable-driven (dark JMAN midnight)
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
          // Legacy keys used by Sidebar.tsx class names
          hover: "hsl(var(--sidebar-accent))",
          active: "hsl(var(--sidebar-primary))",
        },
        // App color tokens
        appColor1: { DEFAULT: "hsl(var(--appColor1))" },
        appColor2: { DEFAULT: "hsl(var(--appColor2))" },
        appColor3: { DEFAULT: "hsl(var(--appColor3))" },
        appColor4: { DEFAULT: "hsl(var(--appColor4))" },
        appColor5: { DEFAULT: "hsl(var(--appColor5))" },
        appColor6: { DEFAULT: "hsl(var(--appColor6))" },
        appColor7: { DEFAULT: "hsl(var(--appColor7))" },
        appColor8: { DEFAULT: "hsl(var(--appColor8))" },
        appColor9: { DEFAULT: "hsl(var(--appColor9))" },
        appColor10: { DEFAULT: "hsl(var(--appColor10))" },
        appColor11: { DEFAULT: "hsl(var(--appColor11))" },

        // -- JMAN Brand Colors ----------------------------------------------
        "jman-midnight": {
          DEFAULT: "#19105B",
          50:  "#F2F2FF",
          100: "#E8E7FF",
          200: "#D3D2FF",
          300: "#B4AEFF",
          400: "#8F7FFF",
          500: "#6A4CFF",
          600: "#5628FF",
          700: "#4916EB",
          800: "#3411A3",
          900: "#19105B",
          950: "#1B076E",
        },
        "jman-trypan": { DEFAULT: "#3411A3" },
        "jman-lightblue": {
          DEFAULT: "#26D4F0",
          50:  "#ECFEFF",
          100: "#CEFAFE",
          200: "#A3F3FD",
          300: "#67E8FA",
          400: "#26D4F0",
          500: "#06B6D6",
          600: "#0391B3",
          700: "#0E7491",
          800: "#145D75",
          900: "#144E64",
          950: "#093344",
        },
        "jman-rose": {
          DEFAULT: "#FF6196",
          50:  "#FFF0F5",
          100: "#FFE3EA",
          200: "#FFCCDC",
          300: "#FFA1BF",
          400: "#FF6196",
          500: "#F93A7F",
          600: "#E7166D",
          700: "#C30D5C",
          800: "#A30F53",
          900: "#8B104D",
          950: "#4E0326",
        },
        "jman-emerald": {
          DEFAULT: "#18978E",
          50:  "#F1FCFA",
          100: "#CFF8F0",
          200: "#9FF0E1",
          300: "#68E1D0",
          400: "#38C9BA",
          500: "#21ADA0",
          600: "#19978E",
          700: "#156F6B",
          800: "#155955",
          900: "#174A48",
          950: "#072C2C",
        },
        "jman-turquoise": {
          DEFAULT: "#71EAE1",
          50:  "#EFFDFB",
          100: "#CDFAF5",
          200: "#9AF4EA",
          300: "#72EAE1",
          400: "#31D1CA",
          500: "#17B5B1",
          600: "#0D9291",
          700: "#117474",
          800: "#125C5D",
          900: "#144C4D",
          950: "#052C2E",
        },
        "jman-amethyst": {
          DEFAULT: "#C36BDB",
          50:  "#FBF6FD",
          100: "#F7EBFC",
          200: "#EED6F8",
          300: "#E3B6F1",
          400: "#D38BE7",
          500: "#C36BDB",
          600: "#A23DBB",
          700: "#88309B",
          800: "#70297F",
          900: "#602768",
          950: "#3C0E44",
        },
        "jman-gray": {
          50:  "#F3F3F7",
          100: "#E8E7EF",
          200: "#D1CFDE",
          300: "#BAB7CE",
          400: "#A39FBD",
          500: "#8C87AD",
          600: "#75709D",
          700: "#5E588C",
          800: "#251C63",
          900: "#47407C",
          950: "#1B076E",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "fade-in": {
          from: { opacity: "0", transform: "translateY(4px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-in": "fade-in 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate"), require("@tailwindcss/typography")],
};

export default config;
